- name: Deploy App
  hosts: web
  become: yes
  gather_facts: false

  tasks:

    - name: Install Docker
      shell: |
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Install docker-compose
      shell: |
        sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Create app directory
      file:
        path: /home/ec2-user/app
        state: directory

    - name: Clone project from GitHub
      git:
        repo: https://github.com/HolmySlimene/ecommerce-devops-lab.git
        dest: /home/ec2-user/app
        version: main

    - name: Run Docker Compose
      shell: |
        cd /home/ec2-user/app
        docker-compose up -d
